import './globals.css';
import localFont from 'next/font/local';
const shabnam = localFont({
  src: '../public/font/Shabnam.woff2',
});
export const metadata = {
  title: 'ecommerce admin',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className={shabnam.className}>{children}</body>
    </html>
  );
}
